// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForSourcingSessionCriteriaProfilesBulkInsert implements pgx.CopyFromSource.
type iteratorForSourcingSessionCriteriaProfilesBulkInsert struct {
	rows                 []SourcingSessionCriteriaProfilesBulkInsertParams
	skippedFirstNextCall bool
}

func (r *iteratorForSourcingSessionCriteriaProfilesBulkInsert) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSourcingSessionCriteriaProfilesBulkInsert) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SourcingSessionCriteriaID,
		r.rows[0].RawProfileID,
		r.rows[0].Score,
		r.rows[0].OrderIndex,
		r.rows[0].CriteriaMatches,
	}, nil
}

func (r iteratorForSourcingSessionCriteriaProfilesBulkInsert) Err() error {
	return nil
}

func (q *Queries) SourcingSessionCriteriaProfilesBulkInsert(ctx context.Context, arg []SourcingSessionCriteriaProfilesBulkInsertParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"sourcing_schema", "sourcing_session_criteria_profile"}, []string{"sourcing_session_criteria_id", "raw_profile_id", "score", "order_index", "criteria_matches"}, &iteratorForSourcingSessionCriteriaProfilesBulkInsert{rows: arg})
}
